apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: xi7en1vky-java-quarkus
  janus-idp.io/tekton: xi7en1vky-java-quarkus
  backstage.io/kubernetes-id: xi7en1vky-java-quarkus
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: xi7en1vky-java-quarkus
resources:
- deployment.yaml
- route.yaml
- service.yaml
